version: "3"

services:
  mysql:
    image: "mysql"
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    env_file:
      - .env.local
    networks:
      - backend-net
    ports:
      - 3306:3306  # Port actuellement exposé pour faciliter les tests sur BDD, à supprimer lors du passage en prod
    restart: always
  api:
    build: api
    ports:
      - 3000:3000
    env_file:
      - .env.local
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
    depends_on:
      - "mysql"
    networks:
      - backend-net
    restart: always

networks:
  backend-net:
    driver: bridge

volumes:
  db-data:
